#pragma once

#include <SDL3/SDL.h>

enum class LRKey {
  LEFT,
  RIGHT
};

enum class Key
{
  // Letters
  A = SDL_SCANCODE_A,
  B = SDL_SCANCODE_B,
  C = SDL_SCANCODE_C,
  D = SDL_SCANCODE_D,
  E = SDL_SCANCODE_E,
  F = SDL_SCANCODE_F,
  G = SDL_SCANCODE_G,
  H = SDL_SCANCODE_H,
  I = SDL_SCANCODE_I,
  J = SDL_SCANCODE_J,
  K = SDL_SCANCODE_K,
  L = SDL_SCANCODE_L,
  M = SDL_SCANCODE_M,
  N = SDL_SCANCODE_N,
  O = SDL_SCANCODE_O,
  P = SDL_SCANCODE_P,
  Q = SDL_SCANCODE_Q,
  R = SDL_SCANCODE_R,
  S = SDL_SCANCODE_S,
  T = SDL_SCANCODE_T,
  U = SDL_SCANCODE_U,
  V = SDL_SCANCODE_V,
  W = SDL_SCANCODE_W,
  X = SDL_SCANCODE_X,
  Y = SDL_SCANCODE_Y,
  Z = SDL_SCANCODE_Z,

  // Numbers
  ONE = SDL_SCANCODE_1,
  TWO = SDL_SCANCODE_2,
  THREE = SDL_SCANCODE_3,
  FOUR = SDL_SCANCODE_4,
  FIVE = SDL_SCANCODE_5,
  SIX = SDL_SCANCODE_6,
  SEVEN = SDL_SCANCODE_7,
  EIGHT = SDL_SCANCODE_8,
  NINE = SDL_SCANCODE_9,
  ZERO = SDL_SCANCODE_0,

  // Function Keys
  F1 = SDL_SCANCODE_F1,
  F2 = SDL_SCANCODE_F2,
  F3 = SDL_SCANCODE_F3,
  F4 = SDL_SCANCODE_F4,
  F5 = SDL_SCANCODE_F5,
  F6 = SDL_SCANCODE_F6,
  F7 = SDL_SCANCODE_F7,
  F8 = SDL_SCANCODE_F8,
  F9 = SDL_SCANCODE_F9,
  F10 = SDL_SCANCODE_F10,
  F11 = SDL_SCANCODE_F11,
  F12 = SDL_SCANCODE_F12,

  // Arrow Keys
  LEFT = SDL_SCANCODE_LEFT,
  RIGHT = SDL_SCANCODE_RIGHT,
  UP = SDL_SCANCODE_UP,
  DOWN = SDL_SCANCODE_DOWN,

  // Modifier Keys
  LSHIFT = SDL_SCANCODE_LSHIFT,
  RSHIFT = SDL_SCANCODE_RSHIFT,
  LCTRL = SDL_SCANCODE_LCTRL,
  RCTRL = SDL_SCANCODE_RCTRL,
  LALT = SDL_SCANCODE_LALT,
  RALT = SDL_SCANCODE_RALT,
  LGUI = SDL_SCANCODE_LGUI, // Left Windows key
  RGUI = SDL_SCANCODE_RGUI, // Right Windows key

  // Enter and Backspace
  ENTER = SDL_SCANCODE_RETURN,
  ESCAPE = SDL_SCANCODE_ESCAPE,
  BACKSPACE = SDL_SCANCODE_BACKSPACE,

  // Space and Tab
  SPACE = SDL_SCANCODE_SPACE,
  TAB = SDL_SCANCODE_TAB,

  // Punctuation Keys
  COMMA = SDL_SCANCODE_COMMA,
  PERIOD = SDL_SCANCODE_PERIOD,
  SLASH = SDL_SCANCODE_SLASH,
  SEMICOLON = SDL_SCANCODE_SEMICOLON,
  APOSTROPHE = SDL_SCANCODE_APOSTROPHE,

  // Brackets and Others
  LEFTBRACKET = SDL_SCANCODE_LEFTBRACKET,
  RIGHTBRACKET = SDL_SCANCODE_RIGHTBRACKET,
  BACKSLASH = SDL_SCANCODE_BACKSLASH,

  // Other Special Keys
  CAPSLOCK = SDL_SCANCODE_CAPSLOCK,
  PRINTSCREEN = SDL_SCANCODE_PRINTSCREEN,
  SCROLLLOCK = SDL_SCANCODE_SCROLLLOCK,
  PAUSE = SDL_SCANCODE_PAUSE,
  INSERT = SDL_SCANCODE_INSERT,
  HOME = SDL_SCANCODE_HOME,
  PAGEUP = SDL_SCANCODE_PAGEUP,
  PAGEDOWN = SDL_SCANCODE_PAGEDOWN,
  DELETE = SDL_SCANCODE_DELETE,
  END = SDL_SCANCODE_END
};